config/routes.rb
Myshoefits::Application.routes.draw do
  root :to => 'welcome#index'

  resources :customers, only: [:create, :index]
  

  get     "signup",   to: "customers#new"
  get     "home",     to: "customers#home"
  post    "addshoe",  to: "customers#addshoe"
  delete  "delshoe",  to: "customers#delshoe"
  get     "predict",  to: "customers#predict"
  get     "index",    to: "customers#index"
  
  get   "signin",   to: "sessions#signin"
  post  "signin",   to: "sessions#signin_attempt"
  get   "signout",  to: "sessions#signout"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_secure_password
  # attr_accessible :CustID, :Email, :Email_confirmation, :Gender, :ShoeSize, :ShoeSizeError, :password, :password_confirmation, :preferredSizeType
  self.primary_key = :CustID
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates_presence_of :Email, :Gender, :password, :preferredSizeType
  # validates_presence_of :password_confirmation
  # validates_presence_of :Email_confirmation
  validates_format_of :Email, with: EMAIL_REGEX, on: :create
  validates_length_of :Email, maximum: 30, message: "Email address should have length less than 30 characters"
  validates_length_of :password, minimum: 8, message: "Password should contain at least 8 characters"
  validates_inclusion_of :Gender, in: ["M","F"]
  validates_inclusion_of :preferredSizeType, in: Sizetype.all

  def Customer.updateShoeStats custid
  	Customer.connection.execute("CALL updateUserShoeStats(#{custid})")
  end

  def Customer.predictSizeToBuy(custid, brand, style, material, sizeType)
    Customer.connection.execute("CALL predictSizeToBuy(#{custid}, '#{brand}', '#{style}', '#{material}', '#{sizeType}')").to_a[0]
  end
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  # attr_accessible :Gender
  self.primary_key = :Gender
end

app/models/lengthfit.rb
class Lengthfit < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  # attr_accessible :ShoeID, :OwnerID, :T2RS_ID, :Brand, :Style, :Material, :Size, :SizeType, :LengthFit, :RealSize
  self.primary_key = :ShoeID

  

  def Shoe.sizeToPreSize(size, sizeType, lengthFit)
  	Shoe.connection.execute(%[SELECT sizeToPreSize(#{size}, "#{sizeType}", "#{lengthFit}");]).to_a[0][0]
  end
end

app/models/shoebrand.rb
class Shoebrand < ActiveRecord::Base
  # attr_accessible :Brand
end

app/models/shoematerial.rb
class Shoematerial < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/shoestyle.rb
class Shoestyle < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/sizetype.rb
class Sizetype < ActiveRecord::Base
  # attr_accessible :SizeType, :MinSize, :MaxSize, :SizeTypeInterval
  self.primary_key = :SizeType
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_customer
  	if session[:CustID]
  		@customer = Customer.find_by_CustID(session[:CustID])
  		return true
  	else
  		redirect_to signin_path
  		return false
  	end
  end

  def save_login_state
  	if session[:CustID]
      @customer = Customer.find_by_CustID(session[:CustID])
  		if @customer
        redirect_to home_path
        return false
      else
        session[:CustID] = nil
        return true
      end
  	else
  		return true
  	end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	
	before_filter :authenticate_customer,	:only => [:home, :addshoe, :delshoe, :predict]
	before_filter :save_login_state,			:only => [:new, :create]

	def new
	end

	def create
		@parms = newcustomer_params
		@lessparms = @parms.reject{|k,v| k == "Email_confirmation"}
		# puts @lessparms
		if @parms["Email"] == @parms["Email_confirmation"]
			@customer = Customer.new(@lessparms)
			@customer.save
			session[:CustID] = @customer.CustID
			session[:preferredSizeType] = Sizetype.find_by_SizeType(@customer.preferredSizeType)
			redirect_to home_path
		else
			flash[:warning] = "Your email address was not entered correctly."
			redirect_to signup_path
		end
	end

	def home
		@shoes = Shoe.where({OwnerID: @customer.CustID}).to_a
	end

	def index
		@customers = Customer.all
	end

	def addshoe
		@parms = newshoe_params
		newShoe = Shoe.new(@parms)
		newPreSize = Shoe.sizeToPreSize(@parms[:Size], @parms[:SizeType], @parms[:LengthFit])
		if (not @customer.ShoeSize) or (newPreSize - @customer.ShoeSize).abs <= 30.0
			newShoe.save
			Customer.updateShoeStats(@customer.CustID)
		else
			flash[:warning] = "You entered a new shoe with a size very different to your previous average shoe size. Please check the size of your new shoe or that of the shoes you have already entered."
		end

		redirect_to home_path
	end

	def delshoe
		@parms = delshoe_params
		Shoe.find_by_ShoeID(@parms[:ShoeID]).destroy
		Customer.updateShoeStats(@customer.CustID)

		redirect_to home_path
	end

	def predict
		@parms = predic_params
		Customer.establish_connection
		results = Customer.predictSizeToBuy(@parms[:CustID], @parms[:Brand], @parms[:Style], @parms[:Material], @parms[:SizeType])
		@parms["prediction"] = results[0]
		@parms["error"] = results[1]
	end

	private
		def newcustomer_params
			params.require(:customer).permit(:Email, :Email_confirmation, :Gender, :password, :password_confirmation, :preferredSizeType)
		end

		def newshoe_params
			params.require(:newshoe).permit(:OwnerID, :Brand, :Style, :Material, :Size, :SizeType, :LengthFit)
		end

		def delshoe_params
			params.require(:delshoe).permit(:ShoeID)
		end

		def predic_params
			params.require(:predic).permit(:CustID, :Brand, :Style, :Material, :SizeType)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  before_filter :save_login_state, 
  	:only => [:signin, :signin_attempt]

  def signin
  end

  def signin_attempt
  	@parms = params[:signin]
  	@customer = Customer.find_by_Email(@parms["Email"])
    if not @customer
      flash[:warning] = "Email address not found. Please try again."
      redirect_to signin_path
  	elsif @customer.authenticate(@parms["password"])
  		session[:CustID] = @customer.CustID
  		redirect_to home_path
  	else
      flash[:warning] = "Incorrect email/password combination"
  		redirect_to signin_path
  	end
  end

  def signout
  	session[:CustID] = nil
  	redirect_to signin_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
		{success: "alert-success", info: "alert-info",	warning: "alert-warning",	danger: "alert-danger"}[flash_type] || flash_type.to_s
	end

	def flash_messages(opts={})
		flash.each do |flash_type, message|
			concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(flash_type)} alert-dismissible", role: "alert") do
				concat content_tag(:button, '<span aria-hidden="true">&times;</span>'.html_safe, class: "close", data: {dismiss: "alert"}, type: "button")
				concat message
			end)
		end
		nil
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/home.html.erb
<h2>My Info</h2>
<table class="table">
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>CustID:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.CustID %></td>
		<div class="col-md-2"></div>
	</tr>
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>Email:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.Email %></td>
		<div class="col-md-2"></div>
	</tr>
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>Password:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.password_digest %></td>
		<div class="col-md-2"></div>
	</tr>
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>ShoeSize:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.ShoeSize %></td>
		<div class="col-md-2"></div>
	</tr>
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>ShoeSizeError:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.ShoeSizeError %></td>
		<div class="col-md-2"></div>
	</tr>
	<tr class="row">
		<div class="col-md-2"></div>
		<td class="col-sm-3 col-md-2"><strong>Preferred SizeType:</strong></td>
		<td class="col-sm-9 col-md-6"><%= @customer.preferredSizeType %></td>
		<div class="col-md-2"></div>
	</tr>
</table>

<h2>My Shoes</h2>
<table class="table">
	<thead>
		<tr class="row">
			<th class="col-md-3 col-sm-3"><strong>Brand</strong></th>
			<th class="col-md-2 col-sm-2"><strong>Style</strong></th>
			<th class="col-md-2 col-sm-2"><strong>Material</strong></th>
			<th class="col-md-1 col-sm-1"><strong>Size</strong></th>
			<th class="col-md-2 col-sm-2"><strong>LengthFit</strong></th>
			<th class="col-md-2 col-sm-2"></th>
		</tr>
	</thead>

	<tbody>
		<% unless @shoes == nil %> <% @shoes.each do |shoe| %>
		<%= form_for :delshoe, url: delshoe_path, method: :delete do |s| %>
			<tr class="row">
				<%= s.hidden_field :ShoeID, :value => shoe[:ShoeID] %>
				<td align="left"><%= shoe[:Brand] %></td>
				<td align="left"><%= shoe[:Style] %></td>
				<td align="left"><%= shoe[:Material] %></td>
				<td align="left"><%= shoe[:Size] %></td>
				<td align="left"><%= shoe[:LengthFit] %></td>
				<td><%= s.submit "Delete shoe", class: "btn btn-danger btn-block" %></td>
			</tr>
		<% end %>
		<% end %> <% end %>

		<%= form_for :newshoe, url: addshoe_path do |s| %>
			<tr class="form-group row">
				<%= s.hidden_field :OwnerID, value: @customer.CustID %>
				<td><%= s.collection_select :Brand, Shoebrand.all, :Brand, :Brand, {}, {class: "form-control"} %></td>
				<td><%= s.collection_select :Style, Shoestyle.all, :Style, :Style, {}, {class: "form-control"} %></td>
				<td><%= s.collection_select :Material, Shoematerial.all, :Material, :Material, {}, {class: "form-control"} %></td>
				<% tempST = Sizetype.find_by_SizeType(@customer.preferredSizeType) %>
				<td><%= s.select :Size, (tempST.MinSize..tempST.MaxSize).step(tempST.SizeTypeInterval).to_a, {}, {class: "form-control"} %> </td>
				<%= s.hidden_field :SizeType, value: tempST.SizeType %>
				<td><%= s.collection_select :LengthFit, Lengthfit.all, :LengthFit, :LengthFit, {}, {class: "form-control"} %></td>
				<td><%= s.submit "Add new shoe", class: "btn btn-success btn-block" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>Shoe Prediction</h2>
<% if @shoes.count >= 3 %>
	<p>Fill in the details of the shoe you intend to buy, and we'll tell you which size you should take!</p>
	<table class="table">
		<thead>
			<tr class="row">
				<th class="col-sm-3 col-md-3">Brand</th>
				<th class="col-sm-2 col-md-2">Style</th>
				<th class="col-sm-2 col-md-2">Material</th>
				<th class="col-sm-2 col-md-2">SizeType</th>
				<th class="col-sm-2 col-md-2"></th>
				<div class="col-sm-1 col-md-1"></div>
			</tr>
		</thead>
		<tbody>
			<%= form_for :predic, url: predict_path do |p| %>
				<tr class="form-group row">
					<td><%= p.collection_select :Brand, Shoebrand.all, :Brand, :Brand, {}, {class: "form-control"} %></td>
					<td><%= p.collection_select :Style, Shoestyle.all, :Style, :Style, {}, {class: "form-control"} %></td>
					<td><%= p.collection_select :Material, Shoematerial.all, :Material, :Material, {}, {class: "form-control"} %></td>
					<td><%= p.collection_select :SizeType, Sizetype.all, :SizeType, :SizeType, {}, {class: "form-control"} %></td>
					<%= p.hidden_field :CustID, :value => @customer.CustID %>
					<td><%= p.submit "Make a prediction", class: "btn btn-success btn-block" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>Unfortunately, you do not have enough registered shoes for us to accurately make predictions for you. Please add at least <%= 3 - @shoes.count %> more shoes to unlock this section.</p>
<% end %>

<p><%= button_to "List of all customers", customers_path, :class => "btn", :method => :get %></p>
<p><%= button_to "Sign out", signout_path, via: :delete, :class => "btn btn-warning", :method => :get %></p>

app/views/customers/index.html.erb
<div class="center hero-unit">
	<h1>List of all customers</h1>

	<br><table class="table table-striped">
		<thead>
			<tr class="row">
				<th class="col-md-1"><strong>CustID</strong></th>
				<th class="col-md-4"><strong>Email</strong></th>
				<th class="col-md-1"><strong>Gender</strong></th>
				<th class="col-md-2"><strong>ShoeSize</strong></th>
				<th class="col-md-2"><strong>ShoeSizeError</strong></th>
				<th class="col-md-2"><strong>Home Page</strong></th>
			</tr>
		</thead>

		<tbody><% @customers.each do |customer| %>
			<tr class="row">
				<td align="right"><%= customer.CustID %></td>
				<td align="left"><%= customer.Email %></td>
				<td align="left"><%= customer.Gender %></td>
				<td align="right"><%= customer.ShoeSize %></td>
				<td align="right"><%= customer.ShoeSizeError %></td>
				<td><%= link_to "Go to customer", home_path(CustID: customer.CustID) %></td>
			</tr>
		<% end %></tbody>
	</table>

	<br><p><%= link_to "New Customer", signup_path %></p>
	<p><%= link_to "Back to Welcome page", controller: "welcome", action: "index" %></p>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1><br>
<%= form_for :customer, url: "customers", html: {class: "form-horizontal", role: "form"} do |f| %>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Email:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<%= f.email_field :Email, class: "form-control", placeholder: "enter your email address here" %>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Confirm Email:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<%= f.email_field :Email_confirmation, class: "form-control", placeholder: "enter the same email address here" %>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Password:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<%= f.password_field :password, class: "form-control", placeholder: "enter your password here" %>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Confirm Password:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<%= f.password_field :password_confirmation, class: "form-control", placeholder: "enter the same password here" %>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Gender:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<label class="col-sm-4 col-md-2 radio-inline">
			<%= f.radio_button :Gender, 'M', checked: true %>Male</label>
			<label class="col-sm-5 col-md-2 radio-inline">
			<%= f.radio_button :Gender, 'F' %>Female</label>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="form-group row">
		<div class="col-md-2"></div>
		<%= f.label "Preferred SizeType:", class: "col-sm-3 col-md-2 control-label" %>
		<div class="col-sm-9 col-md-4">
			<%= f.collection_select :preferredSizeType, Sizetype.all, :SizeType, :SizeType, {}, {class: "form-control"} %>
		</div>
		<div class="col-md-4"></div>
	</div>

	<%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>

<br><p>Already a  user? <%= link_to "Sign in here", signin_path %></p>
<p>Go to the <%= link_to "list of all users", customers_path %></p>

app/views/customers/predict.html.erb
<h1>Prediction</h1>
<p class="row">
	<div class="col-md-4"></div>
	<div class="col-sm-12 col-md-4">
		Based on your data, our amazing algorithms and a little bit of fairy dust, we have concluded that when buying a <%= @parms[:Brand] %> made of <%= @parms[:Material] %> in the <%= @parms[:Style] %> style in the <%= @parms[:SizeType] %> SizeType, the best size for you to buy would be <%= @parms[:prediction] %>, with an uncertainty of <%= @parms[:error] %>.
		</div>
		<div class="col-md-4"></div>
</p>

<%= button_to "Back to my profile", home_path, :class => "btn btn-primary", :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>MyShoeFits</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

	<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle button -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Links-on-the-right">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button><!-- end navbar toggle button -->
				<%= link_to "MyShoeFits", "/", id: "logo", class: "navbar-brand" %>
			</div><!-- end navbar-header -->

			<!-- Items toggleable in small view -->
			<div class="collapse navbar-collapse" id="Links-on-the-right">
				<ul class="nav navbar-nav navbar-right">
					<% if session[:CustID] %>
						<li><%= link_to "Home", home_path %></li>
						<li><%= link_to "Sign out", signout_path %></li>
					<% else %>
						<li><%= link_to "Register", signup_path %></li>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</div><!-- end navbar-collapse -->
		</div> <!-- end container-fluid -->
	</nav>

</head>

<body>
	<div class="container center hero-unit">
		<%= flash_messages %>
		<%= yield %>
	</div>
</body>

</html>

app/views/welcome/index.html.erb
<div class="center hero-unit">
	<h1>Welcome to MyShoeFits</h1>

	<%= button_to "List of all customers", index_path, {class: "btn btn-large btn-primary", method: :get} %><br>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), "http://rubyonrails.org" %>